Enigma/Enigma/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('transfer.urls')),
]

Enigma/transfer/urls.py
from django.urls import path
from . import views

app_name = 'transfer'

urlpatterns = [
    path('',views.homeView, name="home"),
    path('transfer',views.transferView, name="transfer"),
    path('<name>/send',views.sendView.as_view(), name="send"),
    path('sendFile/<pk>',views.sendFileView, name="sendFile"),

    path('<name>/receive', views.receiveView, name="receive"),
    path('<name>/receiveFile', views.receiveFileView, name="receiveFile"),

    path('decryptFile',views.decryptFile, name="decryptFile"),
    path('downloadFile/<file_name>',views.downloadFile, name="downloadFile"),

    # path('message',views.MessagesView.as_view(), name="messages"),
    # path('generateSOS',views.SOS, name="generateSOS"),
    # path('SOS',views.SOSView.as_view(), name="SOS"),
    # path('SOS/location/<pk>', views.location, name='location'),
    # path('files', views.FilesView.as_view(), name="files"),
    # path('file/<username>',views.FileUploadView.as_view(), name="uploadFile"),
    # path('download/<file_name>', views.downloadFile, name="download"),
    # path('check/<file_name>', views.checkFile, name="check"),
]

Enigma/transfer/models.py
from django.db import models
from .AES_module import AES
from .ECC_module import ECC
from .Convert import converter
import ast

class File(models.Model):
    sender = models.CharField(max_length=50)
    receiver = models.CharField(max_length=50)
    file = models.FileField(upload_to='transfer/uploads/')
    aes_key = models.CharField(max_length=40)
    ecc_public = models.CharField(max_length=350)
    file_type = models.CharField(max_length=5)

    C1_aesKey = models.CharField(max_length=350)
    C2_aesKey = models.CharField(max_length=350)

    C1_multimedia = models.CharField(max_length=350)
    C2_multimedia = models.CharField(max_length=350)

    def get_file_type(self):
        self.file_type = str(self.file).split(".")[1]

    def encrypt_AES_key(self):
        ecc_obj_AESkey = ECC.ECC()
        (self.C1_aesKey, self.C2_aesKey) = ecc_obj_AESkey.encryption(ast.literal_eval(self.ecc_public), str(int(self.aes_key)))

    def encrypt_multimedia(self):
        multimedia_data = converter.fileToBase64(str(self.file))
        aes = AES.AES(int(self.aes_key))
        encrypted_multimedia = aes.encryptBigData(multimedia_data)
        data_for_ecc = converter.makeSingleString(encrypted_multimedia)
        ecc = ECC.ECC()
        (self.C1_multimedia, self.C2_multimedia) = ecc.encryption(ast.literal_eval(self.ecc_public), data_for_ecc)

Enigma/transfer/views.py
from django.views import generic
from django.shortcuts import render,redirect
from django.views.generic.edit import CreateView
from .models import *
from .ECC_module import ECC
from django.http import HttpResponse, HttpResponseRedirect
from django.views.decorators.csrf import csrf_exempt
import json
import ast
from rest_framework.views import APIView

from rest_framework.response import Response
import mimetypes,os
from django.utils.encoding import smart_str
from wsgiref.util import FileWrapper




# Create your views here.


def homeView(request):
    return render(request, "transfer/home.html")

def transferView(request):
    name=request.POST['name']
    context={
        'name': name
    }
    return render(request, "transfer/transfer.html", context)

class sendView(CreateView):
    model = File
    fields = ['receiver', 'aes_key', 'file', 'ecc_public']
    sender = ''

    def dispatch(self, request, *args, **kwargs):
        self.sender = self.kwargs['name']
        if request.method.lower() in self.http_method_names:
            handler = getattr(self, request.method.lower(), self.http_method_not_allowed)
        else:
            handler = self.http_method_not_allowed
        return handler(request, *args, **kwargs)

    def form_valid(self, form):
        form.instance.sender = self.sender
        if form.is_valid():
            form.save()
            file = File.objects.get(file=form.instance.file)
            file.get_file_type()
            file.encrypt_AES_key()
            file.encrypt_multimedia()
            file.save()
            file_pk=file.pk
            return redirect('transfer:sendFile', file_pk)




def sendFileView(request,pk):
    file=File.objects.get(pk=pk)
    context={
        "file":file
    }
    return render(request, "transfer/home.html", context)


def receiveView(request, name):
    context = {
        'name': name
    }
    return render(request, "transfer/receive.html", context)


def receiveFileView(request, name):
    ecc_private_key=request.POST["ecc_private"]
    ecc_obj_AESkey = ECC.ECC()
    ecc_public_key = ecc_obj_AESkey.gen_pubKey(int(ecc_private_key))
    context={
        "name":name,
        "ecc_private_key": ecc_private_key,
        "ecc_public_key":ecc_public_key
    }
    return render(request, "transfer/receiveFile.html", context)

@csrf_exempt
def decryptFile(request):
    # if the request method is a POST request
    if request.method == 'POST':
        # content sent via XMLHttpRequests can be accessed in request.body
        # and it comes in a JSON string, that's why we use json library to
        # turn it into a normal dictionary again
        msg_obj = json.loads(request.body)

        # tries to create the message and save it in the db
        file_name = msg_obj['file_name'][17:]
        C1_aesKey = ast.literal_eval(msg_obj['C1_aesKey'])
        C2_aesKey = int(msg_obj['C2_aesKey'])
        C1_multimedia = ast.literal_eval(msg_obj['C1_multimedia'])
        C2_multimedia = int(msg_obj['C2_multimedia'])
        private_key = int(msg_obj["ecc_private"])

        ecc_AESkey = ECC.ECC()
        decryptedAESkey = ecc_AESkey.decryption(C1_aesKey, C2_aesKey, private_key)

        ecc_obj = ECC.ECC()
        encrypted_multimedia = ecc_obj.decryption(C1_multimedia, C2_multimedia, private_key)
        clean_data_list = converter.makeListFromString(encrypted_multimedia)

        aes_obj = AES.AES(int(decryptedAESkey))
        decrypted_multimedia = aes_obj.decryptBigData(clean_data_list)


        output_file = "transfer/downloads/" + file_name
        converter.base64ToFile(decrypted_multimedia, output_file)
        data={
            'file_name': file_name
        }

        return HttpResponse(json.dumps({'file_name': file_name}), content_type="application/json")


    else:
        return HttpResponseRedirect('/')


def downloadFile(request,file_name):
    file_path = 'transfer/downloads/'+file_name
    file_wrapper = FileWrapper(open(file_path,'rb'))
    file_mimetype = mimetypes.guess_type(file_path)
    response = HttpResponse(file_wrapper, content_type=file_mimetype )
    response['X-Sendfile'] = file_path
    response['Content-Length'] = os.stat(file_path).st_size
    response['Content-Disposition'] = 'attachment; filename=%s/' % smart_str(file_name)
    return response

Enigma/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
{% load static %}
<head>
	<title>{% block title %} {% endblock %}</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	{% comment %}
<!--===============================================================================================-->
	<link rel="icon" type="image/png" href='{% static "images/icons/favicon.ico" %}'/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href='{% static "vendor/bootstrap/css/bootstrap.min.css" %}'>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href='{% static "fonts/font-awesome-4.7.0/css/font-awesome.min.css" %}'>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href='{% static "vendor/animate/animate.css" %}'>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href='{% static "vendor/css-hamburgers/hamburgers.min.css" %}'>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href='{% static "vendor/select2/select2.min.css" %}'>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href='{% static "css/util.css" %}'>
	<link rel="stylesheet" type="text/css" href='{% static "css/main.css" %}'>
<!--===============================================================================================-->
<!--===============================================================================================-->
	<script src='{% static "vendor/jquery/jquery-3.2.1.min.js" %}'></script>
<!--===============================================================================================-->
	<script src='{% static "vendor/bootstrap/js/popper.js" %}'></script>
	<script src='{% static "vendor/bootstrap/js/bootstrap.min.js" %}'></script>
<!--===============================================================================================-->
	<script src='{% static "vendor/select2/select2.min.js" %}'></script>
<!--===============================================================================================-->
	<script src='{% static "vendor/tilt/tilt.jquery.min.js" %}'></script>

	
	{% endcomment %}
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    {% block extra-head %}
    {% endblock %}

</head>
<body>

	<div class="contact1">
		<div class="container-contact1">
			{% block body %}
            {% endblock %}
		</div>
	</div>




	{% comment %}

	<script >
		$('.js-tilt').tilt({
			scale: 1.1
		})
	</script>


<!--===============================================================================================-->
	<script src='{% static "js/main.js" %}'></script>
	{% endcomment %}

</body>
</html>

Enigma/templates/transfer/file_form.html
 {%  extends 'base.html' %}
{% load staticfiles %}

{% block extra-head %}
<script src="http://localhost:4000/socket.io/socket.io.js"></script>
{% endblock %}

{%  block body %}


    <form id="send" action="" method="post" enctype="multipart/form-data" style="margin-left: 25%;">
        {% csrf_token %}
        <div class="wrap-input1 validate-input" data-validate = "Receiver is required">
            <input id="receiver" class="input1" type="text" name="receiver" placeholder="Receiver nickname">
            <span class="shadow-input1"></span>
        </div>

        <div class="wrap-input1 validate-input" data-validate = "AES-Key is required">
            <input class="input1" type="text" name="aes_key" placeholder="AES-Key">
            <span class="shadow-input1"></span>
        </div>


        <div class="ecc_input validate-input" data-validate = "ECC-Public-Key is required" style="display: none">
            <input id="ecc_public" class="input1" type="text" name="ecc_public" placeholder="ECC-Public-Key">
            <span class="shadow-input1"></span>
        </div>

        <div class="wrap-input2 validate-input" data-validate = "File is required">
            <input class="input2" type="file" name="file" placeholder="File">
            <span class="shadow-input2"></span>
        </div>


        <div class="container-contact1-form-btn" style="display: none;">
            <button class="contact1-form-btn">
                <span>
                    Send
                </span>
            </button>
        </div>

    </form>

    <script>
    var host = 'localhost';
    var port = '4000';

    var socket = io(host + ':' + port);
    var receivers=[];
    socket.on('getReceive', function(msgObject) {
        if($("#receiver").val()==msgObject['receiver']){
            $("#ecc_public").val(msgObject["ecc_public"]);
            if ($("#ecc_public").val()) {
                $(".container-contact1-form-btn").show();
                $(".ecc_input").show();
            }
        }
        receivers.push(msgObject);
    });

    $("#receiver").change(function () {
        receiver=$(this).val();
        $.each(receivers,function (index,r) {
            if(receiver==r['receiver']){
                $("#ecc_public").val(r["ecc_public"]);
                if ($("#ecc_public").val()) {
                    $(".container-contact1-form-btn").show();
                    $(".ecc_input").show();
                }
            }
        })
    })
    $("#send").submit(function (e) {
        {#e.preventDefault();#}
        console.log($("#ecc_public").val());
    })





    </script>

{% endblock %}

Enigma/templates/transfer/home.html
{%  extends 'base.html' %}
{% load staticfiles %}
{% block title %}
Enigma
{% endblock %}

{% block body %}
    <div class="contact1-pic js-tilt" data-tilt>
        <img src='{% static "images/img-01.png" %}' alt="IMG">
    </div>

    <form class="contact1-form validate-form" action="{% url 'transfer:transfer' %}" method="post">
        {% csrf_token %}
        <span class="contact1-form-title">
            Enter a nickname
        </span>

        <div class="wrap-input1 validate-input" data-validate = "Nickname is required">
            <input class="input1" type="text" name="name" placeholder="Nickname">
            <span class="shadow-input1"></span>
        </div>

        <div class="container-contact1-form-btn">
            <button class="contact1-form-btn">
                <span>
                    Start Transferring
                    <i class="fa fa-long-arrow-right" aria-hidden="true"></i>
                </span>
            </button>
        </div>
    </form>

    {% if file %}
        <script src="http://localhost:4000/socket.io/socket.io.js"></script>

        <script>

            var host = 'localhost';
            var port = '4000';

            var socket = io(host + ':' + port);

            msgObject={
                'sender' : "{{ file.sender }}",
                'receiver' : "{{ file.receiver }}",
                'file_name' : "{{ file.file }}",
                'C1_aesKey' : "{{ file.C1_aesKey }}",
                'C2_aesKey' : "{{ file.C2_aesKey }}",
                'C1_multimedia' : "{{ file.C1_multimedia}}",
                'C2_multimedia' : "{{ file.C2_multimedia}}",
            }

            socket.emit('send', msgObject);
            console.log("emitted");

        </script>

    {% endif %}
{% endblock %}

Enigma/templates/transfer/receive.html
{%  extends 'base.html' %}
{% load staticfiles %}
{% block title %}
Enigma
{% endblock %}

{% block body %}
    <form class="contact1-form validate-form" action='{% url "transfer:receiveFile" name %}' method="post">
        {% csrf_token %}

        <div class="wrap-input1 validate-input" data-validate = "ECC Private Key is required">
            <input id="ecc_private" class="input1" type="text" name="ecc_private" placeholder="ECC Pivate Key">
            <span class="shadow-input1"></span>
        </div>

        <div class="container-contact1-form-btn">
            <button id="receive" class="contact1-form-btn">
                <span>
                    Receive
                </span>
            </button>
        </div>
    </form>

{% endblock %}

Enigma/templates/transfer/receiveFile.html
{%  extends 'base.html' %}
{% load staticfiles %}
{% block title %}
Enigma
{% endblock %}

{% block extra-head %}
<script src="http://localhost:4000/socket.io/socket.io.js"></script>
{% endblock %}

{% block body %}
    <p id="status">

    </p>

    <script>


    var host = 'localhost';
    var port = '4000';

    var socket = io(host + ':' + port);

    xhttp = new XMLHttpRequest();
    receiver="{{ name }}";
    ecc_public="{{ ecc_public_key }}";
    msgObject = {
        'receiver': receiver,
        'ecc_public': ecc_public,
    };
    socket.emit('receive', msgObject);
    $("#status").text("Receiving...")
    console.log("emitted");

    socket.on('getSend', function(msgObject) {
        $("#status").text("File Received from "+msgObject['sender']+". Decrypting......");
        console.log(msgObject['sender']);
        msgObject["ecc_private"]="{{ ecc_private_key }}";
        {#xhttp.open('POST', '{% url "transfer:decryptFile" %}', true);#}
        {#// sends the data to the view#}
        {#xhttp.send(JSON.stringify(msgObject));#}

        $.ajax({
            type: 'POST',
            url: '{% url "transfer:decryptFile" %}',
            data: JSON.stringify(msgObject), // or JSON.stringify ({name: 'jonas'}),
            success: function(data) {
                console.log('data: ' + data['file_name']);
                $("#status").text("Decrypted");
                downloadLink="</br><a href='http://127.0.0.1:8000/downloadFile/"+data['file_name']+"'>Click Here to download</a>";
                $("#status").append(downloadLink)
                },
            contentType: "application/json",
            dataType: 'json'
        });

        console.log("Download");

    });
    </script>
{% endblock %}

Enigma/templates/transfer/send.html
{%  extends 'base.html' %}
{% load staticfiles %}
{% block title %}
Enigma
{% endblock %}



{% block body %}

    <div class="contact1-pic js-tilt" data-tilt>
        <img src='{% static "images/send.jpeg" %}' alt="IMG">
    </div>

    <form class="contact1-form validate-form" action='{% url "transfer:sendFile" file.pk %}' method="post">
        {% csrf_token %}

        <div class="wrap-input1 validate-input" data-validate = "Nickname is required">
            <input class="input1" type="text" name="receiver" placeholder="Nickname">
            <span class="shadow-input1"></span>
        </div>

        <div class="wrap-input2 validate-input" data-validate = "File is required">
            <input class="input2" type="file" name="file" placeholder="File">
            <span class="shadow-input2"></span>
        </div>

        <div class="container-contact1-form-btn">
            <button class="contact1-form-btn">
                <span>
                    Send
                </span>
            </button>
        </div>
    </form>
{% endblock %}

Enigma/templates/transfer/transfer.html
{%  extends 'base.html' %}
{% load staticfiles %}
{% block title %}
Enigma
{% endblock %}

{% block body %}
    <figure>
        <img src='{% static "images/send.jpeg" %}'>
        <figcaption>
            <div class="container-contact1-form-btn">
                <a href='{% url "transfer:send" name %}'><button id="send" class="contact1-form-btn">
                    <span>
                        Send
                    </span>
                </button></a>
            </div>
        </figcaption>
    </figure>
    <figure>
        <img src='{% static "images/receive.jpeg" %}'>
        <figcaption>
            <div class="container-contact1-form-btn">
                <a href='{% url "transfer:receive" name %}'><button id="receive" class="contact1-form-btn">
                    <span>
                        Receive
                    </span>
                </button></a>
            </div>
        </figcaption>
    </figure>

    <script>

    $("#send").click(function () {

    })
    </script>

{% endblock %}